import type { Achievement } from '../types';

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_workout',
    title: 'Primeiro Passo',
    description: 'Completou seu primeiro treino no Gym-Up.',
    icon: 'trophy',
    xpReward: 100,
    category: 'milestone',
  },
  {
    id: 'streak_3',
    title: 'Ritmo Aquecido',
    description: 'Manteve uma sequência de 3 dias consecutivos de treino.',
    icon: 'flame',
    xpReward: 150,
    category: 'streak',
  },
  {
    id: 'streak_7',
    title: 'Disciplina de Ferro',
    description: 'Treinou por 7 dias seguidos sem furar.',
    icon: 'zap',
    xpReward: 300,
    category: 'streak',
  },
  {
    id: 'sets_50',
    title: 'Fome de Repetições',
    description: 'Concluiu um total de 50 séries anotadas.',
    icon: 'repeat',
    xpReward: 200,
    category: 'volume',
  },
  {
    id: 'sets_200',
    title: 'Centurião do Aço',
    description: 'Completou mais de 200 séries com disciplina total.',
    icon: 'shield',
    xpReward: 500,
    category: 'volume',
  },
  {
    id: 'volume_10k',
    title: '10.000 kg Movidos',
    description: 'Movimentou mais de 10.000 kg somando todas as séries.',
    icon: 'trending-up',
    xpReward: 350,
    category: 'volume',
  },
  {
    id: 'leg_day_champion',
    title: 'Membro Inferior Honrado',
    description: 'Concluiu um treino focado em pernas sem pular exercícios.',
    icon: 'award',
    xpReward: 150,
    category: 'mastery',
  },
  {
    id: 'month_master',
    title: 'Mestre da Consistência',
    description: 'Completou 12 ou mais treinos no mesmo mês.',
    icon: 'calendar',
    xpReward: 600,
    category: 'milestone',
  },
  {
    id: 'level_5',
    title: 'Guerreiro da Academia',
    description: 'Alcançou o Nível 5 no Gym-Up.',
    icon: 'star',
    xpReward: 400,
    category: 'mastery',
  },
];
