import type { WorkoutPlan } from '../types';

export interface DefaultPlanOption {
  id: 'beginner' | 'intermediate' | 'advanced';
  title: string;
  subtitle: string;
  levelBadge: string;
  daysCount: number;
  minutesPerSession: number;
  description: string;
  highlights: string[];
  plan: WorkoutPlan;
}

export const DEFAULT_PLANS: Record<'beginner' | 'intermediate' | 'advanced', DefaultPlanOption> = {
  beginner: {
    id: 'beginner',
    title: 'Treino Iniciante (Adaptação & Full Body)',
    subtitle: '3 dias por semana • 50 min/sessão',
    levelBadge: '🌱 Iniciante',
    daysCount: 3,
    minutesPerSession: 50,
    description:
      'Focado em adaptação neuromuscular, postura e domínio dos movimentos fundamentais em máquinas e halteres.',
    highlights: [
      '3 treinos por semana em dias alternados (ex: Seg / Qua / Sex)',
      'Estímulo equilibrado de corpo inteiro para rápida evolução inicial',
      'Volume moderado para evitar sobrecarga articular precoce',
    ],
    plan: {
      id: 'default-plan-beginner',
      title: 'Treino Padrão Iniciante (Full Body 3x)',
      description:
        'Programa estruturado para adaptação e ganho de força inicial com segurança e biomecânica balanceada.',
      createdAt: new Date().toISOString(),
      answers: {
        goal: 'general',
        daysPerWeek: 3,
        minutesPerSession: 50,
        experience: 'beginner',
        equipment: 'full_gym',
        focusMuscles: ['Peitoral', 'Costas', 'Quadríceps'],
        limitations: 'Adaptação inicial',
      },
      days: [
        {
          id: 'day-1',
          name: 'Treino A - Corpo Inteiro (Empurrar & Puxar)',
          dayOfWeekLabel: 'Segunda-feira',
          targetMuscleGroups: ['Peitoral', 'Costas', 'Quadríceps', 'Core'],
          estimatedMinutes: 50,
          exercises: [
            {
              id: 'ex-beg-1',
              name: 'Leg Press 45° ou Horizontal',
              muscleGroup: 'Quadríceps e Glúteos',
              equipment: 'Máquina',
              notes: 'Pés na largura dos ombros, desça até 90° sem arredondar a lombar.',
              targetSets: [
                { setNumber: 1, targetReps: '12-15', suggestedWeightKg: 40, restSeconds: 60 },
                { setNumber: 2, targetReps: '12-15', suggestedWeightKg: 50, restSeconds: 60 },
                { setNumber: 3, targetReps: '10-12', suggestedWeightKg: 60, restSeconds: 60 },
              ],
            },
            {
              id: 'ex-beg-2',
              name: 'Supino Reto na Máquina / Halteres',
              muscleGroup: 'Peitoral',
              equipment: 'Máquina / Halteres',
              notes: 'Mantenha escápulas fechadas e controle a fase excêntrica.',
              targetSets: [
                { setNumber: 1, targetReps: '12-15', suggestedWeightKg: 10, restSeconds: 60 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 12, restSeconds: 60 },
                { setNumber: 3, targetReps: '10-12', suggestedWeightKg: 14, restSeconds: 60 },
              ],
            },
            {
              id: 'ex-beg-3',
              name: 'Puxada Frontal Aberta na Polia',
              muscleGroup: 'Costas (Dorsal)',
              equipment: 'Polia Alta',
              notes: 'Puxe a barra em direção ao peitoral superior, sem inclinar o tronco excessivamente.',
              targetSets: [
                { setNumber: 1, targetReps: '12-15', suggestedWeightKg: 25, restSeconds: 60 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 30, restSeconds: 60 },
                { setNumber: 3, targetReps: '10-12', suggestedWeightKg: 35, restSeconds: 60 },
              ],
            },
            {
              id: 'ex-beg-4',
              name: 'Elevação Lateral com Halteres',
              muscleGroup: 'Ombros (Deltoide Lateral)',
              equipment: 'Halteres',
              notes: 'Cotovelos levemente flexionados, suba até a linha dos ombros.',
              targetSets: [
                { setNumber: 1, targetReps: '12-15', suggestedWeightKg: 4, restSeconds: 45 },
                { setNumber: 2, targetReps: '12-15', suggestedWeightKg: 5, restSeconds: 45 },
                { setNumber: 3, targetReps: '10-12', suggestedWeightKg: 6, restSeconds: 45 },
              ],
            },
            {
              id: 'ex-beg-5',
              name: 'Abdominal Crunch no Colchonete',
              muscleGroup: 'Abdômen / Core',
              equipment: 'Colchonete',
              notes: 'Concentre a força no abdômen sem puxar a cervical com as mãos.',
              targetSets: [
                { setNumber: 1, targetReps: '15-20', suggestedWeightKg: 0, restSeconds: 45 },
                { setNumber: 2, targetReps: '15-20', suggestedWeightKg: 0, restSeconds: 45 },
                { setNumber: 3, targetReps: '15-20', suggestedWeightKg: 0, restSeconds: 45 },
              ],
            },
          ],
        },
        {
          id: 'day-2',
          name: 'Treino B - Membros Inferiores & Braços',
          dayOfWeekLabel: 'Quarta-feira',
          targetMuscleGroups: ['Posteriores', 'Glúteos', 'Bíceps', 'Tríceps', 'Panturrilhas'],
          estimatedMinutes: 50,
          exercises: [
            {
              id: 'ex-beg-6',
              name: 'Cadeira Flexora',
              muscleGroup: 'Posterior de Coxa',
              equipment: 'Máquina',
              notes: 'Segure 1 segundo no final do movimento e volte devagar.',
              targetSets: [
                { setNumber: 1, targetReps: '12-15', suggestedWeightKg: 20, restSeconds: 60 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 25, restSeconds: 60 },
                { setNumber: 3, targetReps: '10-12', suggestedWeightKg: 30, restSeconds: 60 },
              ],
            },
            {
              id: 'ex-beg-7',
              name: 'Cadeira Extensora',
              muscleGroup: 'Quadríceps',
              equipment: 'Máquina',
              notes: 'Estenda os joelhos sem trancar bruscamente a articulação.',
              targetSets: [
                { setNumber: 1, targetReps: '12-15', suggestedWeightKg: 25, restSeconds: 60 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 30, restSeconds: 60 },
                { setNumber: 3, targetReps: '10-12', suggestedWeightKg: 35, restSeconds: 60 },
              ],
            },
            {
              id: 'ex-beg-8',
              name: 'Rosca Direta na Polia ou com Halteres',
              muscleGroup: 'Bíceps',
              equipment: 'Polia / Halteres',
              notes: 'Cotovelos firmes ao lado do tronco durante toda a execução.',
              targetSets: [
                { setNumber: 1, targetReps: '12-15', suggestedWeightKg: 10, restSeconds: 45 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 12, restSeconds: 45 },
                { setNumber: 3, targetReps: '10-12', suggestedWeightKg: 14, restSeconds: 45 },
              ],
            },
            {
              id: 'ex-beg-9',
              name: 'Tríceps Corda na Polia',
              muscleGroup: 'Tríceps',
              equipment: 'Polia',
              notes: 'Abra a ponta das cordas embaixo para contração total.',
              targetSets: [
                { setNumber: 1, targetReps: '12-15', suggestedWeightKg: 12, restSeconds: 45 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 15, restSeconds: 45 },
                { setNumber: 3, targetReps: '10-12', suggestedWeightKg: 17, restSeconds: 45 },
              ],
            },
            {
              id: 'ex-beg-10',
              name: 'Gêmeos em Pé (Panturrilhas)',
              muscleGroup: 'Panturrilhas',
              equipment: 'Degrau / Máquina',
              notes: 'Alongue bem embaixo e segure 1s na ponta dos pés.',
              targetSets: [
                { setNumber: 1, targetReps: '15-20', suggestedWeightKg: 20, restSeconds: 45 },
                { setNumber: 2, targetReps: '15-20', suggestedWeightKg: 30, restSeconds: 45 },
                { setNumber: 3, targetReps: '15-20', suggestedWeightKg: 35, restSeconds: 45 },
              ],
            },
          ],
        },
        {
          id: 'day-3',
          name: 'Treino C - Tronco Completo & Funcional',
          dayOfWeekLabel: 'Sexta-feira',
          targetMuscleGroups: ['Costas', 'Peitoral', 'Ombros', 'Core'],
          estimatedMinutes: 50,
          exercises: [
            {
              id: 'ex-beg-11',
              name: 'Remada Baixa no Triângulo',
              muscleGroup: 'Costas e Trapézio',
              equipment: 'Polia Baixa',
              notes: 'Puxe o triângulo até o umbigo mantendo o peito estufado.',
              targetSets: [
                { setNumber: 1, targetReps: '12-15', suggestedWeightKg: 25, restSeconds: 60 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 30, restSeconds: 60 },
                { setNumber: 3, targetReps: '10-12', suggestedWeightKg: 35, restSeconds: 60 },
              ],
            },
            {
              id: 'ex-beg-12',
              name: 'Crucifixo na Máquina (Peck Deck)',
              muscleGroup: 'Peitoral',
              equipment: 'Máquina',
              notes: 'Sinta o alongamento no peitoral sem forçar excessivamente os ombros.',
              targetSets: [
                { setNumber: 1, targetReps: '12-15', suggestedWeightKg: 20, restSeconds: 60 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 25, restSeconds: 60 },
                { setNumber: 3, targetReps: '10-12', suggestedWeightKg: 30, restSeconds: 60 },
              ],
            },
            {
              id: 'ex-beg-13',
              name: 'Desenvolvimento Máquina ou Halteres',
              muscleGroup: 'Ombros',
              equipment: 'Máquina / Halteres',
              notes: 'Empurre verticalmente mantendo a coluna apoiada.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 8, restSeconds: 60 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 10, restSeconds: 60 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 12, restSeconds: 60 },
              ],
            },
            {
              id: 'ex-beg-14',
              name: 'Prancha Isométrica',
              muscleGroup: 'Core / Lombar',
              equipment: 'Colchonete',
              notes: 'Corpo alinhado em linha reta da cabeça aos calcanhares.',
              targetSets: [
                { setNumber: 1, targetReps: '30 seg', suggestedWeightKg: 0, restSeconds: 45 },
                { setNumber: 2, targetReps: '30 seg', suggestedWeightKg: 0, restSeconds: 45 },
                { setNumber: 3, targetReps: '30 seg', suggestedWeightKg: 0, restSeconds: 45 },
              ],
            },
          ],
        },
      ],
    },
  },

  intermediate: {
    id: 'intermediate',
    title: 'Treino Intermediário (Push / Pull / Legs / Upper)',
    subtitle: '4 dias por semana • 60 min/sessão',
    levelBadge: '⚡ Intermediário',
    daysCount: 4,
    minutesPerSession: 60,
    description:
      'Divisão clássica e altamente eficiente para hipertrofia, progressão de carga e ganho de volume muscular.',
    highlights: [
      'Divisão balanceada Push (Empurrar), Pull (Puxar), Legs (Pernas) e Upper (Superiores)',
      'Combina exercícios livres com pesos livres e máquinas de isolamento',
      'Descanso ótimo entre grupos musculares para máxima recuperação',
    ],
    plan: {
      id: 'default-plan-intermediate',
      title: 'Treino Padrão Intermediário (PPL + Upper 4x)',
      description:
        'Divisão equilibrada de 4 dias para ganho de massa magra, densidade muscular e progressão contínua de cargas.',
      createdAt: new Date().toISOString(),
      answers: {
        goal: 'hypertrophy',
        daysPerWeek: 4,
        minutesPerSession: 60,
        experience: 'intermediate',
        equipment: 'full_gym',
        focusMuscles: ['Peitoral', 'Costas', 'Ombros', 'Pernas'],
        limitations: 'Nenhuma',
      },
      days: [
        {
          id: 'day-1',
          name: 'Treino A - Peitoral, Ombros & Tríceps (Push)',
          dayOfWeekLabel: 'Segunda-feira',
          targetMuscleGroups: ['Peitoral', 'Ombros', 'Tríceps'],
          estimatedMinutes: 60,
          exercises: [
            {
              id: 'ex-int-1',
              name: 'Supino Reto com Barra ou Halteres',
              muscleGroup: 'Peitoral Maior',
              equipment: 'Banco + Halteres / Barra',
              notes: 'Desça controlando a carga em 2s e empurre com força.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 18, restSeconds: 60 },
                { setNumber: 2, targetReps: '8-10', suggestedWeightKg: 20, restSeconds: 75 },
                { setNumber: 3, targetReps: '6-8', suggestedWeightKg: 22, restSeconds: 90 },
                { setNumber: 4, targetReps: '8-10', suggestedWeightKg: 20, restSeconds: 75 },
              ],
            },
            {
              id: 'ex-int-2',
              name: 'Supino Inclinado com Halteres (30°)',
              muscleGroup: 'Peitoral Superior',
              equipment: 'Banco Inclinado + Halteres',
              notes: 'Foco na contração da porção clavicular do peito.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 14, restSeconds: 60 },
                { setNumber: 2, targetReps: '8-10', suggestedWeightKg: 16, restSeconds: 60 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 16, restSeconds: 60 },
              ],
            },
            {
              id: 'ex-int-3',
              name: 'Desenvolvimento com Halteres Sentado',
              muscleGroup: 'Ombros (Deltoide Anterior/Médio)',
              equipment: 'Halteres',
              notes: 'Mantenha os cotovelos ligeiramente à frente da linha do corpo.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 12, restSeconds: 60 },
                { setNumber: 2, targetReps: '8-10', suggestedWeightKg: 14, restSeconds: 60 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 14, restSeconds: 60 },
              ],
            },
            {
              id: 'ex-int-4',
              name: 'Elevação Lateral na Polia ou Halteres',
              muscleGroup: 'Deltoide Lateral',
              equipment: 'Polia / Halteres',
              notes: 'Eleve sem usar impulso corporal.',
              targetSets: [
                { setNumber: 1, targetReps: '12-15', suggestedWeightKg: 8, restSeconds: 45 },
                { setNumber: 2, targetReps: '12-15', suggestedWeightKg: 8, restSeconds: 45 },
                { setNumber: 3, targetReps: '10-12', suggestedWeightKg: 10, restSeconds: 45 },
              ],
            },
            {
              id: 'ex-int-5',
              name: 'Tríceps Testa com Barra W / Halteres',
              muscleGroup: 'Tríceps',
              equipment: 'Barra W / Halteres',
              notes: 'Cotovelos apontados para o teto durante toda a série.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 16, restSeconds: 60 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 18, restSeconds: 60 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 20, restSeconds: 60 },
              ],
            },
          ],
        },
        {
          id: 'day-2',
          name: 'Treino B - Costas, Bíceps & Trapézio (Pull)',
          dayOfWeekLabel: 'Terça-feira',
          targetMuscleGroups: ['Costas', 'Bíceps', 'Trapézio', 'Deltoide Posterior'],
          estimatedMinutes: 60,
          exercises: [
            {
              id: 'ex-int-6',
              name: 'Puxada Alta Aberta no Pulley',
              muscleGroup: 'Grande Dorsal',
              equipment: 'Polia Alta',
              notes: 'Puxe focando em aproximar as escápulas.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 45, restSeconds: 60 },
                { setNumber: 2, targetReps: '8-10', suggestedWeightKg: 50, restSeconds: 75 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 55, restSeconds: 75 },
                { setNumber: 4, targetReps: '8-10', suggestedWeightKg: 50, restSeconds: 60 },
              ],
            },
            {
              id: 'ex-int-7',
              name: 'Remada Curvada com Barra ou Halteres',
              muscleGroup: 'Costas (Espessura)',
              equipment: 'Barra / Halteres',
              notes: 'Tronco a 45°, puxe a barra na direção do umbigo.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 30, restSeconds: 60 },
                { setNumber: 2, targetReps: '8-10', suggestedWeightKg: 35, restSeconds: 75 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 40, restSeconds: 75 },
              ],
            },
            {
              id: 'ex-int-8',
              name: 'Crucifixo Invertido no Peck Deck / Halteres',
              muscleGroup: 'Deltoide Posterior e Romboides',
              equipment: 'Máquina / Halteres',
              notes: 'Excelente para correção postural e densidade posterior.',
              targetSets: [
                { setNumber: 1, targetReps: '12-15', suggestedWeightKg: 25, restSeconds: 45 },
                { setNumber: 2, targetReps: '12-15', suggestedWeightKg: 30, restSeconds: 45 },
                { setNumber: 3, targetReps: '10-12', suggestedWeightKg: 35, restSeconds: 45 },
              ],
            },
            {
              id: 'ex-int-9',
              name: 'Rosca Direta com Barra W',
              muscleGroup: 'Bíceps',
              equipment: 'Barra W',
              notes: 'Sem balanço do tronco durante a subida.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 18, restSeconds: 60 },
                { setNumber: 2, targetReps: '8-10', suggestedWeightKg: 20, restSeconds: 60 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 22, restSeconds: 60 },
              ],
            },
            {
              id: 'ex-int-10',
              name: 'Rosca Martelo com Halteres',
              muscleGroup: 'Braquial e Antebraço',
              equipment: 'Halteres',
              notes: 'Pegada neutra para volume e espessura do braço.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 12, restSeconds: 45 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 14, restSeconds: 45 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 16, restSeconds: 60 },
              ],
            },
          ],
        },
        {
          id: 'day-3',
          name: 'Treino C - Pernas Completas & Panturrilhas (Legs)',
          dayOfWeekLabel: 'Quinta-feira',
          targetMuscleGroups: ['Quadríceps', 'Posteriores', 'Glúteos', 'Panturrilhas'],
          estimatedMinutes: 60,
          exercises: [
            {
              id: 'ex-int-11',
              name: 'Agachamento Livre ou no Smith',
              muscleGroup: 'Quadríceps e Glúteos',
              equipment: 'Barra / Smith',
              notes: 'Profundidade segura, mantendo os calcanhares colados no chão.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 40, restSeconds: 90 },
                { setNumber: 2, targetReps: '8-10', suggestedWeightKg: 50, restSeconds: 90 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 60, restSeconds: 90 },
                { setNumber: 4, targetReps: '6-8', suggestedWeightKg: 70, restSeconds: 120 },
              ],
            },
            {
              id: 'ex-int-12',
              name: 'Leg Press 45°',
              muscleGroup: 'Quadríceps',
              equipment: 'Máquina',
              notes: 'Desça com máxima amplitude sem tirar a pelve do banco.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 100, restSeconds: 75 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 120, restSeconds: 75 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 140, restSeconds: 90 },
              ],
            },
            {
              id: 'ex-int-13',
              name: 'Mesa ou Cadeira Flexora',
              muscleGroup: 'Posteriores de Coxa',
              equipment: 'Máquina',
              notes: 'Pico de contração de 1s no ponto de flexão.',
              targetSets: [
                { setNumber: 1, targetReps: '12-15', suggestedWeightKg: 35, restSeconds: 60 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 40, restSeconds: 60 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 45, restSeconds: 60 },
              ],
            },
            {
              id: 'ex-int-14',
              name: 'Stiff com Halteres ou Barra',
              muscleGroup: 'Isquiotibiais e Glúteos',
              equipment: 'Halteres',
              notes: 'Quadril para trás com a coluna ereta.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 16, restSeconds: 60 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 18, restSeconds: 60 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 20, restSeconds: 60 },
              ],
            },
            {
              id: 'ex-int-15',
              name: 'Panturrilha em Pé ou Sentado',
              muscleGroup: 'Panturrilhas',
              equipment: 'Máquina',
              notes: 'Cadência controlada: 2s subindo, 2s descendo.',
              targetSets: [
                { setNumber: 1, targetReps: '15-20', suggestedWeightKg: 40, restSeconds: 45 },
                { setNumber: 2, targetReps: '15-20', suggestedWeightKg: 50, restSeconds: 45 },
                { setNumber: 3, targetReps: '12-15', suggestedWeightKg: 55, restSeconds: 45 },
              ],
            },
          ],
        },
        {
          id: 'day-4',
          name: 'Treino D - Superior Geral & Core (Upper Focus)',
          dayOfWeekLabel: 'Sexta-feira',
          targetMuscleGroups: ['Peitoral', 'Costas', 'Ombros', 'Abdômen'],
          estimatedMinutes: 55,
          exercises: [
            {
              id: 'ex-int-16',
              name: 'Crucifixo Inclinado ou Crossover na Polia',
              muscleGroup: 'Peitoral Superior / Médio',
              equipment: 'Polia / Halteres',
              notes: 'Foco no pico de contração no meio.',
              targetSets: [
                { setNumber: 1, targetReps: '12-15', suggestedWeightKg: 12, restSeconds: 45 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 14, restSeconds: 45 },
                { setNumber: 3, targetReps: '10-12', suggestedWeightKg: 14, restSeconds: 45 },
              ],
            },
            {
              id: 'ex-int-17',
              name: 'Remada Serrote com Halter',
              muscleGroup: 'Costas (Dorsal Unilateral)',
              equipment: 'Halter',
              notes: 'Apoie a perna oposta no banco e puxe em direção ao quadril.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 18, restSeconds: 60 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 20, restSeconds: 60 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 22, restSeconds: 60 },
              ],
            },
            {
              id: 'ex-int-18',
              name: 'Desenvolvimento Arnold com Halteres',
              muscleGroup: 'Ombros',
              equipment: 'Halteres',
              notes: 'Gire os punhos suavemente durante a subida.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 10, restSeconds: 60 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 12, restSeconds: 60 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 14, restSeconds: 60 },
              ],
            },
            {
              id: 'ex-int-19',
              name: 'Abdominal Infra na Paralela / Colchonete',
              muscleGroup: 'Abdômen Inferior',
              equipment: 'Paralela / Colchonete',
              notes: 'Eleve os joelhos enrolando a pelve em direção ao tórax.',
              targetSets: [
                { setNumber: 1, targetReps: '15-20', suggestedWeightKg: 0, restSeconds: 45 },
                { setNumber: 2, targetReps: '15-20', suggestedWeightKg: 0, restSeconds: 45 },
                { setNumber: 3, targetReps: '15-20', suggestedWeightKg: 0, restSeconds: 45 },
              ],
            },
          ],
        },
      ],
    },
  },

  advanced: {
    id: 'advanced',
    title: 'Treino Avançado (ABCDE de Alta Intensidade)',
    subtitle: '5 dias por semana • 65 min/sessão',
    levelBadge: '🔥 Avançado',
    daysCount: 5,
    minutesPerSession: 65,
    description:
      'Treino de alta especificidade e volume isolado para cada agrupamento muscular, com técnicas de intensidade e periodização.',
    highlights: [
      '5 sessões especializadas (Peito, Costas, Pernas A, Ombros & Braços, Pernas B)',
      'Máxima sobrecarga progressiva e estímulos variados',
      'Ideal para quem treina há mais de 2 anos com rotina consistente',
    ],
    plan: {
      id: 'default-plan-advanced',
      title: 'Treino Padrão Avançado (ABCDE 5x)',
      description:
        'Divisão avançada com volume otimizado por agrupamento muscular, foco em hipertrofia máxima e densidade.',
      createdAt: new Date().toISOString(),
      answers: {
        goal: 'hypertrophy',
        daysPerWeek: 5,
        minutesPerSession: 65,
        experience: 'advanced',
        equipment: 'full_gym',
        focusMuscles: ['Peitoral', 'Costas', 'Ombros', 'Braços', 'Pernas'],
        limitations: 'Nenhuma',
      },
      days: [
        {
          id: 'day-1',
          name: 'Treino A - Peitoral & Deltoide Anterior',
          dayOfWeekLabel: 'Segunda-feira',
          targetMuscleGroups: ['Peitoral', 'Deltoide Anterior'],
          estimatedMinutes: 65,
          exercises: [
            {
              id: 'ex-adv-1',
              name: 'Supino Inclinado com Halteres Pesados',
              muscleGroup: 'Peitoral Superior',
              equipment: 'Banco 30° + Halteres',
              notes: 'Prioridade na porção clavicular. Controle a descida.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 22, restSeconds: 75 },
                { setNumber: 2, targetReps: '8-10', suggestedWeightKg: 26, restSeconds: 90 },
                { setNumber: 3, targetReps: '6-8', suggestedWeightKg: 30, restSeconds: 90 },
                { setNumber: 4, targetReps: '6-8', suggestedWeightKg: 32, restSeconds: 90 },
              ],
            },
            {
              id: 'ex-adv-2',
              name: 'Supino Reto com Barra',
              muscleGroup: 'Peitoral Geral',
              equipment: 'Barra Olímpica',
              notes: 'Toque o esterno com controle e empurre explosivamente.',
              targetSets: [
                { setNumber: 1, targetReps: '8-10', suggestedWeightKg: 60, restSeconds: 90 },
                { setNumber: 2, targetReps: '6-8', suggestedWeightKg: 70, restSeconds: 90 },
                { setNumber: 3, targetReps: '6-8', suggestedWeightKg: 80, restSeconds: 90 },
              ],
            },
            {
              id: 'ex-adv-3',
              name: 'Crucifixo na Polia (Crossover Médio)',
              muscleGroup: 'Peitoral Médio / Inferior',
              equipment: 'Polia Dupla',
              notes: 'Aperte o peitoral por 1 segundo no pico de contração.',
              targetSets: [
                { setNumber: 1, targetReps: '12-15', suggestedWeightKg: 15, restSeconds: 60 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 18, restSeconds: 60 },
                { setNumber: 3, targetReps: '10-12', suggestedWeightKg: 20, restSeconds: 60 },
              ],
            },
            {
              id: 'ex-adv-4',
              name: 'Paralelas com Peso Corporal ou Adicional',
              muscleGroup: 'Peitoral Inferior e Tríceps',
              equipment: 'Barras Paralelas',
              notes: 'Incline o tronco à frente para recrutar mais peitoral.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 0, restSeconds: 75 },
                { setNumber: 2, targetReps: '8-10', suggestedWeightKg: 0, restSeconds: 75 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 0, restSeconds: 75 },
              ],
            },
          ],
        },
        {
          id: 'day-2',
          name: 'Treino B - Costas & Deltoide Posterior',
          dayOfWeekLabel: 'Terça-feira',
          targetMuscleGroups: ['Costas', 'Dorsal', 'Deltoide Posterior', 'Trapézio'],
          estimatedMinutes: 65,
          exercises: [
            {
              id: 'ex-adv-5',
              name: 'Barra Fixa (Pronada ou Neutra)',
              muscleGroup: 'Dorsal e Costas',
              equipment: 'Barra Fixa',
              notes: 'Amplitude completa do alongamento até o queixo passar da barra.',
              targetSets: [
                { setNumber: 1, targetReps: '8-10', suggestedWeightKg: 0, restSeconds: 90 },
                { setNumber: 2, targetReps: '8-10', suggestedWeightKg: 0, restSeconds: 90 },
                { setNumber: 3, targetReps: '6-8', suggestedWeightKg: 0, restSeconds: 90 },
              ],
            },
            {
              id: 'ex-adv-6',
              name: 'Remada Cavalinho com Barra T',
              muscleGroup: 'Espessura de Costas e Romboides',
              equipment: 'Barra T',
              notes: 'Mantenha a lombar travada e puxe com as costas.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 40, restSeconds: 75 },
                { setNumber: 2, targetReps: '8-10', suggestedWeightKg: 50, restSeconds: 90 },
                { setNumber: 3, targetReps: '6-8', suggestedWeightKg: 60, restSeconds: 90 },
                { setNumber: 4, targetReps: '8-10', suggestedWeightKg: 50, restSeconds: 75 },
              ],
            },
            {
              id: 'ex-adv-7',
              name: 'Puxada com Triângulo no Pulley',
              muscleGroup: 'Grande Dorsal',
              equipment: 'Polia Alta',
              notes: 'Puxe até o peito e segure 1 segundo.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 55, restSeconds: 60 },
                { setNumber: 2, targetReps: '8-10', suggestedWeightKg: 60, restSeconds: 60 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 65, restSeconds: 75 },
              ],
            },
            {
              id: 'ex-adv-8',
              name: 'Face Pull na Polia com Corda',
              muscleGroup: 'Deltoide Posterior e Manguito',
              equipment: 'Polia + Corda',
              notes: 'Puxe na altura dos olhos e abra as mãos no final.',
              targetSets: [
                { setNumber: 1, targetReps: '12-15', suggestedWeightKg: 25, restSeconds: 45 },
                { setNumber: 2, targetReps: '12-15', suggestedWeightKg: 30, restSeconds: 45 },
                { setNumber: 3, targetReps: '12-15', suggestedWeightKg: 30, restSeconds: 45 },
              ],
            },
          ],
        },
        {
          id: 'day-3',
          name: 'Treino C - Quadríceps & Panturrilhas',
          dayOfWeekLabel: 'Quarta-feira',
          targetMuscleGroups: ['Quadríceps', 'Adutores', 'Panturrilhas'],
          estimatedMinutes: 65,
          exercises: [
            {
              id: 'ex-adv-9',
              name: 'Agachamento Livre com Barra',
              muscleGroup: 'Quadríceps e Core',
              equipment: 'Barra Olímpica',
              notes: 'Base firme, peito erguido e controle milimétrico.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 60, restSeconds: 90 },
                { setNumber: 2, targetReps: '8-10', suggestedWeightKg: 80, restSeconds: 120 },
                { setNumber: 3, targetReps: '6-8', suggestedWeightKg: 95, restSeconds: 120 },
                { setNumber: 4, targetReps: '6-8', suggestedWeightKg: 105, restSeconds: 120 },
              ],
            },
            {
              id: 'ex-adv-10',
              name: 'Hack Squat ou Leg Press 45°',
              muscleGroup: 'Quadríceps',
              equipment: 'Máquina Hack',
              notes: 'Pés na parte baixa da plataforma para foco em quadríceps.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 80, restSeconds: 90 },
                { setNumber: 2, targetReps: '8-10', suggestedWeightKg: 100, restSeconds: 90 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 120, restSeconds: 90 },
              ],
            },
            {
              id: 'ex-adv-11',
              name: 'Cadeira Extensora (Drop-set na última)',
              muscleGroup: 'Quadríceps (Reto Femoral)',
              equipment: 'Máquina',
              notes: 'Contração de 2s no topo. Na última série, reduza 30% da carga e continue.',
              targetSets: [
                { setNumber: 1, targetReps: '12-15', suggestedWeightKg: 45, restSeconds: 60 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 55, restSeconds: 60 },
                { setNumber: 3, targetReps: '10-12', suggestedWeightKg: 65, restSeconds: 60 },
              ],
            },
            {
              id: 'ex-adv-12',
              name: 'Gêmeos Sentado na Máquina',
              muscleGroup: 'Panturrilhas (Sóleo)',
              equipment: 'Máquina Sóleo',
              notes: 'Amplitude total sem quicar o peso.',
              targetSets: [
                { setNumber: 1, targetReps: '15-20', suggestedWeightKg: 35, restSeconds: 45 },
                { setNumber: 2, targetReps: '15-20', suggestedWeightKg: 45, restSeconds: 45 },
                { setNumber: 3, targetReps: '15-20', suggestedWeightKg: 50, restSeconds: 45 },
              ],
            },
          ],
        },
        {
          id: 'day-4',
          name: 'Treino D - Ombros Completos & Braços (Bíceps + Tríceps)',
          dayOfWeekLabel: 'Quinta-feira',
          targetMuscleGroups: ['Deltoides', 'Bíceps', 'Tríceps'],
          estimatedMinutes: 65,
          exercises: [
            {
              id: 'ex-adv-13',
              name: 'Desenvolvimento Militar com Barra em Pé',
              muscleGroup: 'Ombros e Core',
              equipment: 'Barra',
              notes: 'Glúteos e abdômen contraídos para proteção lombar.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 30, restSeconds: 75 },
                { setNumber: 2, targetReps: '8-10', suggestedWeightKg: 36, restSeconds: 90 },
                { setNumber: 3, targetReps: '6-8', suggestedWeightKg: 42, restSeconds: 90 },
              ],
            },
            {
              id: 'ex-adv-14',
              name: 'Elevação Lateral com Halteres (Pirâmide)',
              muscleGroup: 'Deltoide Lateral',
              equipment: 'Halteres',
              notes: 'Suba com os cotovelos guiando o movimento.',
              targetSets: [
                { setNumber: 1, targetReps: '12-15', suggestedWeightKg: 10, restSeconds: 45 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 12, restSeconds: 45 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 14, restSeconds: 60 },
                { setNumber: 4, targetReps: '12-15', suggestedWeightKg: 8, restSeconds: 45 },
              ],
            },
            {
              id: 'ex-adv-15',
              name: 'Super-série: Rosca Direta Barra W + Tríceps Francês',
              muscleGroup: 'Bíceps e Tríceps',
              equipment: 'Barra W / Halter',
              notes: 'Execute o exercício de bíceps e vá direto para o tríceps antes de descansar.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 20, restSeconds: 60 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 24, restSeconds: 60 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 28, restSeconds: 75 },
              ],
            },
            {
              id: 'ex-adv-16',
              name: 'Super-série: Rosca Martelo + Tríceps Pulley Corda',
              muscleGroup: 'Braquial e Tríceps Lateral',
              equipment: 'Halteres e Polia',
              notes: 'Sem intervalo entre os dois exercícios.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 14, restSeconds: 60 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 16, restSeconds: 60 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 18, restSeconds: 60 },
              ],
            },
          ],
        },
        {
          id: 'day-5',
          name: 'Treino E - Posteriores de Coxa, Glúteos & Core',
          dayOfWeekLabel: 'Sexta-feira',
          targetMuscleGroups: ['Posteriores', 'Glúteos', 'Lombar', 'Abdômen'],
          estimatedMinutes: 60,
          exercises: [
            {
              id: 'ex-adv-17',
              name: 'Levantamento Terra Romeno (RDL)',
              muscleGroup: 'Isquiotibiais e Glúteos',
              equipment: 'Barra',
              notes: 'Foco no alongamento profundo dos posteriores na descida.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 50, restSeconds: 90 },
                { setNumber: 2, targetReps: '8-10', suggestedWeightKg: 70, restSeconds: 90 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 85, restSeconds: 90 },
                { setNumber: 4, targetReps: '6-8', suggestedWeightKg: 95, restSeconds: 120 },
              ],
            },
            {
              id: 'ex-adv-18',
              name: 'Mesa Flexora Unilateral',
              muscleGroup: 'Posterior de Coxa',
              equipment: 'Máquina',
              notes: 'Foco na simetria de força entre as pernas.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 20, restSeconds: 60 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 25, restSeconds: 60 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 30, restSeconds: 60 },
              ],
            },
            {
              id: 'ex-adv-19',
              name: 'Elevação Pélvica com Barra ou Máquina',
              muscleGroup: 'Glúteos',
              equipment: 'Barra / Máquina',
              notes: 'Contração máxima de 2s no topo.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 60, restSeconds: 75 },
                { setNumber: 2, targetReps: '8-10', suggestedWeightKg: 80, restSeconds: 90 },
                { setNumber: 3, targetReps: '8-10', suggestedWeightKg: 90, restSeconds: 90 },
              ],
            },
            {
              id: 'ex-adv-20',
              name: 'Prancha Abdominal com Roda / Colchonete',
              muscleGroup: 'Core e Abdômen',
              equipment: 'Roda Abdominal / Colchonete',
              notes: 'Estenda o corpo controlando com o abdômen sem arquear a lombar.',
              targetSets: [
                { setNumber: 1, targetReps: '10-12', suggestedWeightKg: 0, restSeconds: 60 },
                { setNumber: 2, targetReps: '10-12', suggestedWeightKg: 0, restSeconds: 60 },
                { setNumber: 3, targetReps: '10-12', suggestedWeightKg: 0, restSeconds: 60 },
              ],
            },
          ],
        },
      ],
    },
  },
};
